### PR TITLE
Additional strategies for S&P tournament

### LINKED ISSUE #249: Add remaining strategies for S&P tournament
We just need the following strategies:

CALCULATOR
PROBE
PROBE2
PROBE3
HARD_PROBE

### PR DESCRIPTION
**Pull request by marcharper**
This closes #249 by adding Prober, Prober2, Prober3, HardProber, and Calculator. I ran some sample tournaments to compare to S&P's publication. Our output matches theirs fairly closely:

Full S&P Tournament

Leaving out the Prober strategies and switching from Hard GoByMajority to Soft GoByMajority makes a substantial difference:

No Probes, Hard Majority
No Probes, Soft Majority

### CODE REVIEW

**Comment by drvinceknight** [comment]
Cool that these line up with original tournament. Will work my way through slowly :)

**Comment by meatballs** [comment]
Great that we can start to point at previous papers and get close to reproducing their work!

**Comment by marcharper** [comment]
Travis seems to be stalling out for some reason -- I get no errors from the unittest suite locally.

**Comment by drvinceknight** [comment]
Let me see if I can restart it or something...

**Comment by drvinceknight** [comment]
```
$ coverage run --source=axelrod -m unittest discover
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Have kicked it back off :)

**Comment by marcharper** [comment]
I just merged in the upstream branch and rebuild the assets following the merge of #244, which should resolve any conflicts.

**Comment by marcharper** [comment]
The tests pass locally again -- any idea why Travis is failing?

**Comment by meatballs** [comment]
I'll have a look at this now

**Comment by meatballs** [comment]
I'm happy with this.

**Comment by marcharper** [comment]
I updated the cache and such following PR #254. All the tests pass locally, let's hope travis makes it this time.

**Comment by drvinceknight** [comment]
Just taking a look. Going to restart travis...

**Pull request merged**
