### PR TITLE
Move processes argument from Tournament.__init__ to tournament.play

### PR DESCRIPTION
**Pull request by marcharper**
Re #580

### CODE REVIEW

**Comment by marcharper** [comment]
The build fails on Python 3.4 while building matplotlib, I suspect it's just a travis problem.

**Comment by drvinceknight** [comment]
Have kicked off the build again. I like that you've moved repetitions also.

**Comment by marcharper** [comment]
Actually it just looks that way from the diff, but it could be a good idea to move repetitions as well.

**Comment by drvinceknight** [comment]
Oh yeah! I see that now :) As it's needed for the generator actually perhaps leave it? (haven't had coffee yet) in a way that is part of the tournament and I can imagine a tournament generator that samples the repetitions for each match?

**Comment by marcharper** [comment]
Let's think about it for another PR.

**Comment by drvinceknight** [comment]
Yup. Weird the build failed to install matplotlib again... Have set it off again, I'll take a proper look this morning. I'm guessing it's some temporary problem with Travis....

**Comment by marcharper** [comment]
I can't see any reason why it would fail on just 3.4, so my next thought was some kind of Travis issue as well.

**Comment by drvinceknight** [comment]
It's not getting to the code right, just failing to install matplotlib. For sure a Travis issue...

**Comment by drvinceknight** [comment]
#585 should fix the py3.4 bug (issue with an upstream bug in pyparsing).

**Comment by drvinceknight** [comment]
👍 from me once py3.4 is happy.

**Pull request merged**
