### PR TITLE
Implemented Black, K83R from Axelrod's Second

### PR DESCRIPTION
**Pull request by gaffney2010**
Fingerprints Below

basic_fortran
basic_python
random_fortran
random_python

### CODE REVIEW

**Comment by marcharper** [comment]
Are we sure the memory depth is 5? It's a weird case since you need to know the round number + the last five rounds...

**Comment by drvinceknight** [comment]
> Are we sure the memory depth is 5? It's a weird case since you need to know the round number + the last five rounds.

This is similar to memory one strategies that all have a memory depth of 1 but that act differently on their first move to any other right?

**Comment by gaffney2010** [comment]
You don't need to know the full round number.  If you gave me just the last five moves as a list, I could check if that list is length 5 or not.

**Comment by drvinceknight** [comment]
> You don't need to know the full round number. If you gave me just the last five moves as a list, I could check if that list is length 5 or not.

Even better point :+1:

**Comment by marcharper** [comment]
I guess that's what I'm asking -- on the first move there's no history so it's sort of a special case and players must have a separate rule. Here on rounds say 4, 5, 6 you have to know the round number and then decide from one of two behaviors. So we need to know if there are at least 5 rounds of history already, so we need the size of the history and therefore all of the history. Or is the rule that we can ask "Are there at least X rounds of history?" and then take the minimum needed value of X as the memory depth?

**Comment by marcharper** [comment]
Also think about the case where there's X rounds of initial play and then a behavior that depends on the last Y rounds, where X != Y.

**Comment by marcharper** [comment]
Also, if the implementation was setting a bit if_round_greater_than_five then we usually call that kind of situation infinite memory...

**Comment by drvinceknight** [comment]
> Here on rounds say 4, 5, 6 you have to know the round number and then decide from one of two behaviors. So we need to know if there are at least 5 rounds of history already, so we need the size of the history and therefore all of the history. Or is the rule that we can ask "Are there at least X rounds of history?"

It's a good question. I think that my personal preference would be to define memory as "if you give `history[-memory:]` or `history` you get the same behaviour". I believe this isn't the first strategy that poses this question so I'd suggest we merge as is (based on the mem 1 behaviour/convention it feels right to me that this has mem depth 5). And perhaps aim to implement a test for memory on all players?

**Comment by gaffney2010** [comment]
In this sense, Tit-For-Tat has to know the round number, since there's a special rule for when turn=1, so you have to know the turn number.  But I think it's clear that TFT is memory=1; by analogy, this is memory=5.  And I think it's intuitive; you're allowed to be forgetful.

**Comment by drvinceknight** [comment]
> "if you give history[-memory:] or history you get the same behaviour"

In this particular case if we're on the third turn, `opponent.history=[C, C, C]` then `opponent.history[-5:]` would also be `[C, C, C]`, so:

```
+        if len(opponent.history) < 5:
+            return C
```

would return `C`.

> And perhaps aim to implement a test for memory on all players?

This would potentially assist with #597 (not in finding an algorithm but at least verifying upper bounds on memory lengths).

**Comment by drvinceknight** [comment]
> In this particular case if we're on the third turn with opponent.history=[C, C, C] then opponent.history[-5:] would also be [C, C, C], so:

If we're on the 150th turn then `len(opponent.history[-5:])` is `5` so the rest of the logic kicks in.

**Comment by drvinceknight** [comment]
I've opened https://github.com/Axelrod-Python/Axelrod/issues/1156 as a suggestion for a test (to perhaps move the discussion about the way to go over there).

**Comment by marcharper** [comment]
Ok, let's discuss elsewhere. I'll merge as is.

**Pull request merged**
