### PR TITLE
Copyright and licence stuff

### LINKED ISSUE #615: Authors in license
Currently the license just has my name to it, I imagine this is just a relic of when I started the library. I suggest we put the code devs there or perhaps the Axelrod-Project development team? Is that a done thing? Don't really know what's best.

### PR DESCRIPTION
**Pull request by meatballs**
Closes #615

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looks great to me. :+1:

**Comment by marcharper** [comment]
+1 from me, @langner ?

**Comment by langner** [comment]
+1

**Comment by langner** [comment]
I'm fine with this, but I would just add that I like the previous version
better. It might not be legally meaningful, but it's sensible and easily
understood. This is in some way "incorrect", since implicitly one expects
all contributors to own the copyright.

**Pull request merged**
