### PR TITLE
Update pattern string

### PR DESCRIPTION
**Pull request by mojones**
I re-ran the evolutionary algorithm to take account of the recently-added strategies.

### CODE REVIEW

**Comment by drvinceknight** [comment]
:warning: do not merge: @mojones has asked on the gitter channel to check if this gives an improved performance. Once someone has the time/computer time to check this write it down here.

**Comment by marcharper** [comment]
Do we want to run both at the same time?

**Comment by drvinceknight** [comment]
> Do we want to run both at the same time?

I've set it running at home. Not both but with this as a replacement, does both make sense thought? We wouldn't have both in the library... (would we?)

**Comment by marcharper** [comment]
There are several strategies that have many variants (5 of each of Hard and Soft GoByMajority). If these two behave significantly differently I don't see any reason not to have both. It would be nice to have some qualitatively different tables (e.g other than n=2=m). Even n=m=1 could be nice even if it's not the best, or n=2, m=1 (and of course one can hope for n, m > 2).

**Comment by drvinceknight** [comment]
> If these two behave significantly differently I don't see any reason not to have both. It would be nice to have some qualitatively different tables (e.g other than n=2=m). Even n=m=1 could be nice even if it's not the best, or n=2, m=1 (and of course one can hope for n, m > 2).

Yeah I think I agree although I would suggest that this is an incremental change? And having each an every incremental change would not really be worth it? Having ones with different size tables would be great.

Just heading home so hopefully will be showing you the results on gitter shortly :) (will also throw them here)

**Comment by marcharper** [comment]
No, I certainly wouldn't recommend adding every incremental change. Let's see how different the results are before getting too theoretical in this discussion.

**Comment by drvinceknight** [comment]
Here's the updated version (pdf format):

[tuned.pdf](https://github.com/Axelrod-Python/Axelrod/files/34232/tuned.pdf)

Current master branch is here:

**Comment by drvinceknight** [comment]
In terms of this strategy being an update of the originally evolved version I would suggest merging this in as is (ie that this is an incremental yet very effective improvement).

**Comment by drvinceknight** [comment]
https://github.com/Axelrod-Python/tournament/pull/18 has all the new results ready in case we're happy.

**Comment by mojones** [comment]
I propose merging as is to replace the current version. I think the stable of strategies is more "interesting" the more diverse it is i.e. having strategies that are fundamentally different. Maybe I could evolve an m=n=1 table using identical methods and add it as a separate strategy?

**Comment by drvinceknight** [comment]
Then possibly some with m,n>2 ?(Which could be fine tuned even more once
there's enough computer power etc...)

**Comment by marcharper** [comment]
Sounds good to me. Versions with n=m=1 would be great just as a point of comparison, also n=1, m=2 and n=2, m=1, if it's not too much trouble! I understand n, m > 2 is computationally more difficult.

**Comment by drvinceknight** [comment]
Those sound like good suggestions to me. I assume this is good to merge
Marc?

**Comment by marcharper** [comment]
I tagged it so

**Comment by drvinceknight** [comment]
Sorry was just on my email :) I'll also merge the tournament update now.

**Pull request merged**
