### PR TITLE
Update ultimatum with new commits from master

### PR DESCRIPTION
**Pull request by gaffney2010**
I started from master and merged in ultimatum.  I'm not sure how to build off of ultimatum otherwise.  The only change is the merge.

### CODE REVIEW

**Comment by marcharper** [comment]
Sure, it's really out of date. You could also try rebasing ultimatum onto the latest master, which may be a lot simpler, and if that goes well, we can simply overwrite the ultimatum branch. We have local copies in case anything goes wrong.

**Comment by gaffney2010** [comment]
> You could also try rebasing ultimatum onto the latest master

This is what I'm doing here.  I'm not sure if the PR overwrites the existing ultimatum or not.

**Comment by marcharper** [comment]
Ok, I see (just tried a rebase on #1338 and got essentially the same thing). Since it rebases without any conflicts (as everything is happening in a subdirectory), and the existing tests run fine, I think in this case we should just force push the rebase of ultimatum over the existing ultimatum branch, which effectively fast-forwards the ultimatum branch to the head of the current master. I'm not aware of any way to do this within the github interface.

**Comment by marcharper** [comment]
Ok, so I just pushed the rebase over ultimatum (the original branch is in ultimatum-bak if needed). Let me know if that works for you.

**Comment by gaffney2010** [comment]
That works for me.  I'll close this then.

**Pull request closed without merging**
