### PR TITLE
Refactors payoff.py

### PR DESCRIPTION
**Pull request by meatballs**
1) Splits the payoff_matrix function into two, creating a new function: interaction_payoff which it then calls.
This gives us a function which can be used to obtain the scores for a single interaction of n turns between two players

2) Removes redundant parameters from various payoff functions where they can be derived from the payoff matrix.

### CODE REVIEW

**Comment by drvinceknight** [comment]
This all looks good to me and a nice logical move after our conversation on Thursday.

**Comment by drvinceknight** [comment]
:+1:

**Comment by meatballs** [comment]
And our conversation led me to realised that the payoff_matrix function was double counting each interaction - hence the last commit on this PR!!

**Comment by marcharper** [comment]
:+1:

**Pull request merged**
