### PR TITLE
Stein and rapoport

### PR DESCRIPTION
**Pull request by MariosZoulias**
#379
Stein and Rapoport strategy tobe implemented into axelrod_first

### CODE REVIEW

**Comment by drvinceknight** [comment]
> Accidentally i commited again the refactoring of mutual.py test

OK it would be better if we could avoid these extra commits (they're already in there so it's confusing things). Could you either:

1. Go back to the `master` branch and create a new branch from which to make this changes, then push and create a new PR (the easiest way from a `git` point of view).
2. Go back to the `master` branch, pull all the changes from upstream (`git pull upstream`) then go back to this branch and `git rebase master` and then force push: `git push -f origin SteinAndRapoport`. (This is technically the correct thing to do but might create some errors that we could help work you through).

Let me know how you'd prefer to do this.

Note that the automatic tests are currently failing, this is because you also need to add `scipy` to `requirements.txt`.

**Comment by drvinceknight** [comment]
> Note that the automatic tests are currently failing, this is because you also need to add scipy to requirements.txt.

You will also need to add it to: https://github.com/Axelrod-Python/Axelrod/blob/master/rtd_environment.yml#L5 so that it would read:

```
name: py35
dependencies:
- python=3.5.2
- numpy>=1.9.2
- matplotlib>=1.4.2
- scipy>=0.19.0
```

But don't worry about that just yet, let's get the PR situation sorted first :)

**Comment by MariosZoulias** [comment]
Hello 
I face problems (again ) in submiting my changes :/
I have tryied evetyhing. I dont know whats wrong.
Thank yu (if you want send me a private in gitter)

**Comment by MariosZoulias** [comment]
Forget it i think i made it ;)

**Comment by drvinceknight** [comment]
I'm closing this because I believe that's what you want to do. (We can always reopen if not)

**Pull request closed without merging**
