### PR TITLE
Fix for temporary files on windows.

### LINKED ISSUE #680: Problems running tournaments with restrictive file permissions
Just had an email with the following error:

```
Playing matches:   0%|          | 0/6 [00:00<?, ?it/s]
                                                      

Analysing:   0%|          | 0/60 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    results = tournament.play()
  File "C:\Python34\lib\site-packages\axelrod\tournament.py", line 113, in play
    keep_interactions=keep_interactions)
  File "C:\Python34\lib\site-packages\axelrod\tournament.py", line 129, in _build_result_set
    game=self.game)
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 757, in __init__
    keep_interactions=keep_interactions)
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 1031, in _build_score_related_metrics
    for match in match_chunks:
  File "C:\Python34\lib\site-packages\axelrod\result_set.py", line 889, in read_match_chunks
    with open(self.filename, 'r') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Marcos\\AppData\\Local\\Temp\\tmpwwoqxprr'
```

As far as I can see it looks like there is some problem due to file permissions of where the temporary file was written. I've suggested giving a filename to the `play` call as a fix (hoping it will write the interactions to a place that the user has access to).

I wonder what the best fix is. 

One suggestion I see is to allow for an option in the play method `memory=True` (`False` by default) which would keep all the interactions in memory. **This would not be good for large tournaments obviously** but should be ok for smaller ones. 

This would not be complicated to do (I think?), we would just add methods to the tournament that do the same as the methods that write to file but write to an interactions dictionary that could be passed directly to the `Results` class file...

Any better ideas?

### PR DESCRIPTION
**Pull request by Ducksual**
Closes #680

### CODE REVIEW

**Comment by drvinceknight** [comment]
The travis failure is hypothesis finding a niche case: I'll work on that! :)

```
AssertionError: Lists differ: ['Adaptive', 'Adaptive', 'Coop... != ['Adaptive', 'Cooperator Hunte...
First differing element 1:
Adaptive
Cooperator Hunter
- ['Adaptive', 'Adaptive', 'Cooperator Hunter', 'Adaptive']
+ ['Adaptive', 'Cooperator Hunter', 'Adaptive', 'Adaptive']
```

**Comment by Ducksual** [comment]
I still have 1 outstanding issue with multiprocessing on test_parallel_play.

**Comment by Ducksual** [comment]
Appveyor python 3.5 failed as expected, 3.4 unexpected!

**Comment by drvinceknight** [comment]
Thanks a lot for your work on this @Ducksual, if and when you want to leave it be just let us know and we can pick it up!

**Comment by Ducksual** [comment]
Part of me really wants to get that last green tick but I think I probably won't have a chance to. Glad I could help!

**Comment by drvinceknight** [comment]
> Part of me really wants to get that last green tick but I think I probably won't have a chance to. Glad I could help!

Thank you very much for all your help :) 👍  Sorry you didn't get to do actual game theoretic work. Perhaps next time.

**Comment by drvinceknight** [comment]
Closing this as superseded by #721. Thank you @Ducksual.

**Pull request closed without merging**
