### PR TITLE
Update citations.md

### PR DESCRIPTION
**Pull request by marcharper**

### CODE REVIEW

**Review by meatballs — APPROVED** [review]

**Review by drvinceknight — APPROVED** [review]
Looks great to me, can't imagine what would break but merge once CI is happy :+1:

**Comment by drvinceknight** [comment]
CI is failing on type checking. We don't pin `mypy` install in the CI:

```
python -m pip install mypy
```

Suggestion:

Change the above (here https://github.com/Axelrod-Python/Axelrod/blob/dev/.github/workflows/config.yml#L48) to:

```
python -m pip install mypy==<version that passes>
```

and open an issue to fix/modify at a later date (perhaps it's time for a `requirements_dev.txt` ?).

**Comment by marcharper** [comment]
It's an unrelated type hint issue due to numpy 1.2.0.

```
axelrod/strategies/ann.py:125: error: Incompatible types in assignment (expression has type "ndarray", variable has type "List[int]")
```

**Comment by drvinceknight** [comment]
I've opened https://github.com/Axelrod-Python/Axelrod/pull/1385 that fixes the issues for me locally.

**Pull request merged**
