### PR TITLE
Rebase 220 onto master

### PR DESCRIPTION
**Pull request by marcharper**
The tests were failing on @meatballs merge because in Python 3 dictionaries don't have .iteritems(), .items() is lazy by default. Also `map` is now lazy, so you need to do the list(map(...)) in some contexts.

I did my rebase onto upstream rather than merging; you can see the results [on this branch](https://github.com/marcharper/Axelrod/tree/220-2)

Edit: So that was it -- once those two errors are fixed most of the other test errors are eliminated.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Is this good to be merged now?

**Comment by marcharper** [comment]
I believe so, but I wouldn't mind the @meatballs stamp of approval on the rebase, at least for round_robin.py.

**Comment by drvinceknight** [comment]
This PR doesn't include any documentation for this, do we want to include it in the PR or open another issue? (Ideally I would like the docs to be updated at the same time, to ensure we don't add features without documentation...)

**Comment by drvinceknight** [comment]
> This PR doesn't include any documentation for this, do we want to include it in the PR or open another issue? (Ideally I would like the docs to be updated at the same time, to ensure we don't add features without documentation...)

Let's go for a separate issue as it's a shame to wait longer on this.

Can we close #271 (it is superseded by this right?)?

**Comment by drvinceknight** [comment]
> I believe so, but I wouldn't mind the @meatballs stamp of approval on the rebase, at least for round_robin.py.

Not sure if you want to wait for him to take a quick look? He said he was happy as long as tests pass (I'm happy).

**Comment by marcharper** [comment]
:thumbsup: and yes let's close #271 afterward.

**Comment by meatballs** [comment]
Right, I'm back in the real world and I'm looking at this now.

**Comment by meatballs** [comment]
> This PR doesn't include any documentation for this, do we want to include it in the PR or open another issue? (Ideally I would like the docs to be updated at the same time, to ensure we don't add features without documentation...)

Normally, I'd agree but there's so much going on in this PR that every delay simply adds to the merge conflicts that occur. How about if we merge this and then I work on the docs for what's done so far before adding in the morality metrics themselves?

**Comment by meatballs** [comment]
> Can we close #271 (it is superseded by this right?)?

Yep. Done.

**Comment by meatballs** [comment]
I'm happy with this. Thanks @marcharper for picking up what I missed on #271 

@drvinceknight, I promise not add anything new before this is documented!

**Comment by drvinceknight** [comment]
I think we've all said we're happy with this and waiting for someone else to merge it in :) Here it goes :+1:

**Comment by drvinceknight** [comment]
Well done to you both guys: I know this took a lot of work :+1:

**Pull request merged**
