### PR TITLE
Update bibliography.rst

### PR DESCRIPTION
**Pull request by GGOUSSEAUD**
Added source for BM player.

### CODE REVIEW

**Comment by GGOUSSEAUD** [comment]
Didn't dare do change [Li2014] to [Li2016] because of the cascade changes but I assume it'd be more correct to rename the article following his proper date.

**Comment by drvinceknight** [comment]
There's no harm in this going in as is but you could just include this in your PR with the BM player which I assume is on it's way?

**Comment by drvinceknight** [comment]
> Didn't dare do change [Li2014] to [Li2016] because of the cascade changes but I assume it'd be more correct to rename the article following his proper date.

I'll take care of that and make sure no cascading changes are left (`make html` with sphinx will actually catch them all).

**Comment by GGOUSSEAUD** [comment]
Aye , Im running the test right now which includes:
-bm.py
-test_bm.py
-all_strategies.py (modified)
-_strategies.py (modified)

**Comment by drvinceknight** [comment]
> Aye , Im running the test right now which includes:

Ok, so let's close this PR and include the new reference in the new PR?

**Comment by drvinceknight** [comment]
> Didn't dare do change [Li2014] to [Li2016] because of the cascade changes but I assume it'd be more correct to rename the article following his proper date.

I've pushed a fix to this in this PR: https://github.com/Axelrod-Python/Axelrod/pull/998

**Comment by GGOUSSEAUD** [comment]
Gotcha

**Pull request closed without merging**
