### PR TITLE
Some necessary changes for transformers to be applied to all strategies; additional test to catch implementation issues for new strategies.

### PR DESCRIPTION
**Pull request by marcharper**
We've been fast and loose with how we use `super` (myself included), and in some cases we hit the usual infinite recursion issue when a transformer is applied to a class that uses super in particular ways.

This PR corrects these issues, makes a change to the `staticmethod` testing of transformers to be more robust, and adds in a test to try to apply a transform to every strategy in the library to catch future strategy issues.

Needs to go in after #399 (for `IdentityTransformer`), tests should pass then. I did not add it to #399 since it's already got a :+1:

### CODE REVIEW

**Comment by marcharper** [comment]
Rebased onto latest master

**Comment by marcharper** [comment]
This one is ready for review @drvinceknight @meatballs (should be easy)

**Comment by drvinceknight** [comment]
:+1: Really like the test that checks that the transform works on all strategies.

**Comment by marcharper** [comment]
I learned the hard way when running some tournaments applying transformers to every strategy. Hopefully this will keep anyone else from experiencing the same.

**Pull request merged**
