### PR TITLE
Fixes #161

### LINKED ISSUE #161: Private Methods
Rename instance methods (in all axelrod classes) that are intended for internal use only using the single leading underscore.

https://www.python.org/dev/peps/pep-0008/#id29

This makes the intention of the code clearer and also restricts the methods that are affected by import statements (i.e. internal methods are not imported elsewhere).

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by meatballs** [comment]
Anyone got any thoughts on this one? I'd like to get it merged (or changed or dumped) so we can move on to the other stuff.

**Comment by drvinceknight** [comment]
Sorry for taking a while to get to this. Looks good to me.

**Comment by langner** [comment]
I didn't have the time to read the code.

**Comment by drvinceknight** [comment]
Sorry @langner would you rather I have waited before merging? (apologies if so).

**Comment by langner** [comment]
> Sorry @langner would you rather I have waited before merging? (apologies if so).

Of course not!

**Pull request merged**
