### PR TITLE
Add type hints to calculator

### PR DESCRIPTION
**Pull request by janga1997**
#808 
No errors with mypy. @drvinceknight @marcharper

### CODE REVIEW

**Comment by drvinceknight** [comment]
Great! Could you add the file to `type_tests.sh` please? :)

**Comment by drvinceknight** [comment]
There's a merge conflict in `type_tests.sh` (probably since I merged in your other PRs) @janga1997. Let me know if you need a hand fixing it :)

**Comment by janga1997** [comment]
@drvinceknight Apparently its a lot easier to resolve it on Github itself, if its just a few lines.

**Comment by drvinceknight** [comment]
Merge conflicts have reappeared (since I just merge in that other strategy).

**Comment by janga1997** [comment]
Next time, I think I will do a couple of strategies in one single pull request.

**Comment by janga1997** [comment]
@drvinceknight If you have the time, could you respond to me on #379 ?

**Comment by janga1997** [comment]
@drvinceknight I suppose this PR is good for a merge?

**Pull request merged**
