### PR TITLE
docs/strategies overview update

### PR DESCRIPTION
**Pull request by meatballs**
Work from @lvisintini with my fix for the Random link

### CODE REVIEW

**Comment by lvisintini** [comment]
The preview that file on this branch is
https://github.com/Axelrod-Python/Axelrod/blob/lvisintini-docs/strategies-overview-update/docs/overview_of_strategies.rst

the latest revision is a step in the right direction but, it's not looking good right now :(

**Comment by meatballs** [comment]
That is not how it looks on my local build! Not good.

**Comment by meatballs** [comment]
@lvisintini What version of sphinx are you using? I built with 1.3.1 and all looks fine.

**Comment by meatballs** [comment]
I wonder if that's just the github preview making a mess of it.

**Comment by lvisintini** [comment]
Not really building it.
I'm just going by what the github preview looks like.
If the priority is to get it to work with sphinx and you confirm it looks good, then there is not problem.

**Comment by drvinceknight** [comment]
I've checked this locally and all looks great. I noticed one problem though, when I ran locally the index of strategies created an empty list for this page: http://axelrod.readthedocs.org/en/latest/index_of_strategies.html

In 07edf59 and 7d15170 I simply remove the index (as we're about to revamp the docs I think this is ok for now?) but if that's just a local issue to me (I wonder if it's left over problems with #318 ?) then revert my commits and either way this is good to go :+1:

**Comment by drvinceknight** [comment]
Only small thing is that for me `Random` is now in italics (the only strategy like that). I don't think this is an issue.

**Comment by meatballs** [comment]
Odd. On my local build, the index is fine and Random is not in italics!

We need some form of CI for the docs.

**Comment by meatballs** [comment]
@drvinceknight I'm on sphinx 1.3.1 You?

**Comment by drvinceknight** [comment]
Ah that might be it (not sure what v right now away from machine). Revert
my commits (weird though cause never been a problem before). Based on that
this gets a :+1: from me. @marcharper :+1: the previous version of this so
I think you can  go ahead and merge :)

**Comment by meatballs** [comment]
I've created a version of the docs on readthedocs that builds from this branch and I've reversed the two commits from @drvinceknight 

You can see the overview doc here: http://axelrod.readthedocs.org/en/lvisintini-docs-strategies-overview-update/overview_of_strategies.html

and the index document here: http://axelrod.readthedocs.org/en/lvisintini-docs-strategies-overview-update/index_of_strategies.html

**Comment by drvinceknight** [comment]
Yeah all looks awesome. :+1:

**Comment by drvinceknight** [comment]
Am merging as @marcharper had ok'd a previous version of this.

**Pull request merged**
