### PR TITLE
Add BurnBothEnds strategy

### PR DESCRIPTION
**Pull request by marcharper**
Tests pass locally, seems black wants to reformat a large number of files. I suggest doing that in a separate PR afterward.

### CODE REVIEW

**Review by Nikoleta-v3 — APPROVED** [review]
Looks great 👍🏻 Thank you @marcharper

**Comment by marcharper** [comment]
@drvinceknight PTAL

**Comment by drvinceknight** [comment]
It's failing on `black` due to an upstream update of `black`.

We have not pinned a version of `black` which is installed in the CI here https://github.com/Axelrod-Python/Axelrod/blob/dev/.github/workflows/config.yml#L58.

Two solutions:

1. Pin `black` in [config.yml](https://github.com/Axelrod-Python/Axelrod/blob/dev/.github/workflows/config.yml#L58). (arguably we could move a few of the installs in that config file to `requirements/development.txt`?).
2. Update `black` and run it again over the whole code base.

I'm agnostic: whatever you prefer Marc :)

**Comment by marcharper** [comment]
I'm fine either way. We can pin black in another PR (do you know the version?) but if we're going to rerun black on the entire codebase, let's merge this first.

**Comment by drvinceknight** [comment]
Sounds good to me.

Checking `black` locally:

```
(base) Axelrod(dev): python -m black -l 80 . --check
All done! ✨ 🍰 ✨
186 files would be left unchanged.
(base) Axelrod(dev): python -m pip show black
Name: black
Version: 22.10.0
Summary: The uncompromising code formatter.
Home-page: None
Author: None
Author-email: Łukasz Langa <lukasz@langa.pl>
License: None
Location: /Users/four/anaconda3/lib/python3.8/site-packages
Requires: mypy-extensions, tomli, platformdirs, typing-extensions, pathspec, click
Required-by:
(base) Axelrod(dev):
```

So as far as I can tell `22.10.0` should do the trick. So changing https://github.com/Axelrod-Python/Axelrod/blob/dev/.github/workflows/config.yml#L58 to:

```
python -m pip install black=="22.10.0"
```

Should work.

**Comment by marcharper** [comment]
Merging, opened #1412 to pin black version.

**Pull request merged**
