### PR TITLE
Plot for distribution of head-to-head wins

### PR DESCRIPTION
**Pull request by marcharper**
Re: #248 and #331 (thanks to @meatballs for the heavy lifting!)

This essentially recreates the published list for the [S&P tournament](http://www.nr.com/whp/StewartPlotkinExtortion2012.pdf), which we can now consider "reproduced".

If we are happy with the plot, I'll update the docs and the tournament repository appropriately.

Most Strategies

S&P

### CODE REVIEW

**Comment by meatballs** [comment]
:+1:

**Comment by drvinceknight** [comment]
Could you add a quick snippet about generating this to the docs please?

**Comment by marcharper** [comment]
Let me see if I can update the tournament repo so that we can pull the plots from there.

**Comment by drvinceknight** [comment]
This is great, sorry to be a pain could you add some tests also: along the lines of https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/tests/unit/test_plot.py#L70

**Comment by marcharper** [comment]
I missed one plot (needed to add the new noise plot to the update script). Otherwise the docs look fine when built locally, so this is good to merge once the last plot is added to tournament.

**Comment by drvinceknight** [comment]
> so this is good to merge once the last plot is added to tournament.

I'm happy for you to merge once that's in @marcharper :)

**Pull request merged**
