### PR TITLE
Adding docs for non default arguments

### PR DESCRIPTION
**Pull request by drvinceknight**
- Adding an example and plot for different turns and repetitions
- Adding a different game example
- For both of those am also including a new plot

### CODE REVIEW

**Comment by meatballs** [comment]
:+1:

**Comment by marcharper** [comment]
Do we not require numpy now?

**Comment by drvinceknight** [comment]
> Do we not require numpy now?

Do you mean re:

> The whole library can be used without any other non base Python libraries
> however if you have `matplotlib <http://matplotlib.org/>`_ installed on your
> system (this is installed automatically if you used :code:`pip install axelrod`)
> there are various graphical things coded in and ready to go.

That's old stuff and should have been changed with the PR bringing numpy in as a requirement. I'll fix it with this PR.

**Comment by drvinceknight** [comment]
Done: good catch :)

**Pull request merged**
