### PR TITLE
Adding Marc's repository to readme

### PR DESCRIPTION
**Pull request by drvinceknight**
Just adding a link to @marcharper's repository. Marc, should really be the one to say that this is ok: feel free to change/close without merging Marc, I just had some time so threw this together :)

### CODE REVIEW

**Comment by drvinceknight** [comment]
(I didn't open an issue for this as we chatted about it very briefly on gitter.)

**Comment by marcharper** [comment]
:thumbsup:

**Comment by marcharper** [comment]
I added a ton of neat plots to the examples, check it out!

**Comment by drvinceknight** [comment]
> I added a ton of neat plots to the examples, check it out!

Awesome :)

**Pull request merged**
