### PR TITLE
Fix bug in plot.py and add missing test

### LINKED ISSUE #894: Bug and Testing of plot.py
There is no unit test for the `default_cmap` function and, as a result, there's a bug in the case of matplotlib not being installed.

The coverage report is also showing several other lines in `plot.py` which are not covered by tests.

### PR DESCRIPTION
**Pull request by meatballs**
Fixes #894

### CODE REVIEW

**Comment by drvinceknight** [comment]
Just pushed another commit which ensures the colour bar is correctly placed too.

**Comment by marcharper** [comment]
Looks fine to me. I don't want to squash all these commits... You might consider an interactive rebase `git rebase -i` onto upstream, removing the revert commit and the original commit by omitting them from the list. Then force push to the branch. If you are both fine with the unnecessary commits then just merge.

**Comment by drvinceknight** [comment]
> If you are both fine with the unnecessary commits then just merge.

I'm agnostic, whatever Owen prefers to do.

**Comment by meatballs** [comment]
I'd go with just merging with the reversal et al

**Pull request merged**
