### PR TITLE
Adds a memory two generalization of a zero determinant strategy

### PR DESCRIPTION
**Pull request by marcharper**
Note: rebased on #1097, I will rebase onto master after that's merged

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looks good, any merit to this being in the `zero_determinant.py` file?

**Comment by marcharper** [comment]
I thought about it... but it's really more of a 2x2x0 Gambler that happens to be ZD, i.e. there's no analog of the LRStrategy to base it on, and I'd end up importing stuff from test_lookerup.py and friends.

**Comment by drvinceknight** [comment]
Cool.

**Comment by drvinceknight** [comment]
Looks good to me :+1: (assuming coverage/tests etc...)

**Pull request merged**
