### PR TITLE
Fix contributing guide links #1395

### PR DESCRIPTION
**Pull request by RobPDev**
I also converted the links to HTTPS and as the `.org` resolved to `.io` I changed the README to point to `.io`.

### CODE REVIEW

**Comment by RobPDev** [comment]
I've tried running the failing test locally, using python 3.8 it passes if `types-setuptools` is installed.

**Comment by drvinceknight** [comment]
Thanks for this, your fixes certainly shouldn't affect the type hints so I'm guessing this might be due to an update of `mypy` (?). Could you add `types-setuptools` to this line of the workflow config: https://github.com/Axelrod-Python/Axelrod/blob/dev/.github/workflows/config.yml#L48 to check if that fixes things?

**Comment by RobPDev** [comment]
I've done a bit of testing, `mypy==0.812` passes, `mypy==0.900` requires `types-setuptools`.

`mypy` 0.900 [removed library stubs](https://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html).

**Comment by drvinceknight** [comment]
This looks like it's sorted the problem. Thanks @RobPDev :+1:

**Review by drvinceknight — APPROVED** [review]

**Comment by RobPDev** [comment]
Just noticed this PR hasn't linked to the issue.
Fixes #1395

**Pull request merged**
