### PR TITLE
Add type hints to ann, meta

### PR DESCRIPTION
**Pull request by janga1997**
#808 
In ann.py, I am not really sure what the type of `weights` is supposed to be. I think it should be a list, but it could also be an numpy array? Any other iterable?
In meta.py , What is `team`'s type supposed to be?
I am not sure, but I think these are the last of the strategies to add type hints to.

### CODE REVIEW

**Comment by marcharper** [comment]
`weights` is a list of floats. A numpy array might work but I don't think we ever use it as such.

`team` is a list of player classes I think.

**Comment by drvinceknight** [comment]
I'm not too sure why travis has not run on this: it's only showing 1 successful check...

**Comment by drvinceknight** [comment]
I've run `mypy` locally and get:

```
Axelrod(janga1997-typeHint11): python run_mypy.py 
axelrod/strategies/ann.py:191: error: Argument 4 to "activate" has incompatible type List[int]; expected List[float]
axelrod/strategies/ann.py:195: error: Unsupported operand types for < ("int" and List[float])
axelrod/strategies/meta.py:94: error: Signature of "meta_strategy" incompatible with supertype "MetaPlayer"
axelrod/strategies/meta.py:109: error: Signature of "meta_strategy" incompatible with supertype "MetaPlayer"
axelrod/strategies/meta.py:211: error: Signature of "meta_strategy" incompatible with supertype "MetaPlayer"
axelrod/strategies/meta.py:249: error: Signature of "meta_strategy" incompatible with supertype "MetaPlayer"
axelrod/strategies/meta.py:390: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:390: error: Invalid base class
axelrod/strategies/meta.py:402: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:402: error: Invalid base class
axelrod/strategies/meta.py:413: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:413: error: Invalid base class
axelrod/strategies/meta.py:424: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:424: error: Invalid base class
axelrod/strategies/meta.py:435: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:435: error: Invalid base class
```

This could be due to an updated version of mypy so try `pip install -U mypy`.

**Comment by janga1997** [comment]
@drvinceknight The `Signature` errors have something to do with the `@staticmethod` decorator, although I don't know what.
And `NiceTransformer` imported from `strategy_transformer.py`,and used to define `NiceMetaWinnerEnsemble` is raising the errors.

**Comment by marcharper** [comment]
The staticmethod related error is literally saying that type signature of the child class meta_strategy method is different than the parent class, which is technically correct. It's just not clear why that is an error.

The second issue is a bit more subtle. The decorated classes are created at runtime so the type checker thinks that the base strategy type either doesn't exist or is invalid. This may be a limitation of mypy, and there may be a workaround where we declare these players to be instances or child classes of MetaPlayer.

**Comment by marcharper** [comment]
@janga1997 Do you want break out the ann and apavlov changes so we can merge those while we sort the metaplayer issues?

**Comment by janga1997** [comment]
@marcharper I've not been able to find the time recently.
I removed the commit for the `meta.py` file.

**Comment by drvinceknight** [comment]
We've had some failures back:


```
59.35s$ python run_mypy.py
axelrod/strategies/meta.py:389: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:389: error: Invalid base class
axelrod/strategies/meta.py:401: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:401: error: Invalid base class
axelrod/strategies/meta.py:412: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:412: error: Invalid base class
axelrod/strategies/meta.py:423: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:423: error: Invalid base class
axelrod/strategies/meta.py:434: error: Invalid type "axelrod.strategies.meta.NiceMetaWinnerEnsemble"
axelrod/strategies/meta.py:434: error: Invalid base class
```

**Comment by janga1997** [comment]
@drvinceknight I forgot to remove `meta.py` from `run_mypy`

**Comment by drvinceknight** [comment]
> @drvinceknight I forgot to remove meta.py from run_mypy

Great! Travis is happy (and both `ann.py` and `apavlov.py` are being run through `mypy`: https://github.com/Axelrod-Python/Axelrod/blob/master/run_mypy.py#L14)

**Pull request merged**
