### PR TITLE
Add type hints to mock-player

### PR DESCRIPTION
**Pull request by janga1997**
@marcharper @drvinceknight 
Fixes part of #808 

1. Is the paramter `actions` just a list of actions? That is `List[axelrod.actions.Action]`?

2. I still don't understand what `history` is. I know it is a `list`, but of what I don't know.

3. And I think the type of `state_dist` is `collections.defaultdict`.

### CODE REVIEW

**Comment by marcharper** [comment]
History is a list of actions, same for actions. `state_dist` a defaultdict.

**Comment by janga1997** [comment]
So history has the same type of `actions`. Okay
For `state_dist` should I just keep the type as `collections.defaultdict`?

**Comment by marcharper** [comment]
Yeah I think just a defaultdict.

**Comment by marcharper** [comment]
This one typechecks so far. I'll run the checker again after you make updates for the types you asked about.

**Comment by marcharper** [comment]
Just `__init__ -> None` for this one and then I think it's good.

**Pull request merged**
