### PR TITLE
use random_choice over many calls of random.random

### PR DESCRIPTION
**Pull request by CamDavidsonPilon**
This PR settles on using random_choice over any custom random.random logic. 

- [ ] I may have reversed the logic, I would appreciate someone else to double check I didn't. 
- [x] remove `import random`s
- [x] fix any tests

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Ugh I think coverage is failing due to a rounding error!

**Comment by CamDavidsonPilon** [comment]
Can you all merge with this red?

**Comment by drvinceknight** [comment]
This looks like a nice refactoring. The coverage decrease doesn't bother me too much (it's minor) but will let another core decide if it's worth trying to address. :+1:

**Comment by meatballs** [comment]
I can't get too excited about a 0.001% decrease!

**Comment by drvinceknight** [comment]
> I can't get too excited about a 0.001% decrease!

Not excited as in you think this should be fixed or it can go through?

**Comment by meatballs** [comment]
We should let it through!

**Comment by drvinceknight** [comment]
Thanks for the contribution @CamDavidsonPilon :) :+1:

**Comment by marcharper** [comment]
For posterity: `random_choice` was introduced to the library because `random.choice([C, D])` is not consistent with random seeds across python 2 and 3. However `random.random` is consistent. So it's ok if people want to use `random.random` for various purposes. This PR is of course an improvement -- I'm just noting that when I finished the python 3 compatibility work I only explicitly changed the instances of `random.choice`.

We should probably explain the `random.choice` and `random.random` situation somewhere in the documentation.

**Comment by drvinceknight** [comment]
> We should probably explain the random.choice and random.random situation somewhere in the documentation.

I agree. I'll add a note to #372 as I continue to add to that.

**Pull request merged**
