### PR TITLE
ignore this.

### PR DESCRIPTION
**Pull request by drvinceknight**
Just testing if #600 is fixed.

### CODE REVIEW

**Comment by meatballs** [comment]
Seems to have worked ok.

**Comment by meatballs** [comment]
At last!

**Comment by meatballs** [comment]
The rounding seems to have worked too. No more failures for reducing coverage by 0.001%

**Comment by drvinceknight** [comment]
> At last!

So it doesn't look to be integrated like it used to to me?

The comment on the PR is new: I guess that was that checkbox? But it's not coming up as an integrated test like it used to "2 successful checks" as opposed to 3 (https://www.dropbox.com/s/kaxy9nvql1go3n9/Screenshot%202016-05-31%2010.27.01.png?dl=0)...

Because you've set up coveralls do you perhaps need to authorise it with github here: https://github.com/integrations/coveralls This is what I see there: https://www.dropbox.com/s/59le1twd1tkpj7r/Screenshot%202016-05-31%2010.26.31.png?dl=0

**Comment by meatballs** [comment]
woo hoo!

**Comment by drvinceknight** [comment]
> woo hoo!

Sweet! :) 👍

**Comment by drvinceknight** [comment]
Closes #600

**Pull request closed without merging**
