### PR TITLE
Adds a read the docs config file

### PR DESCRIPTION
**Pull request by alexhroom**
Fixes issues caused by https://github.com/readthedocs/readthedocs.org/issues/10290. originally part of #1419.

### CODE REVIEW

**Comment by alexhroom** [comment]
how weird. a few issues: on the CI,
```
 ERROR: test_normalized_parameters (axelrod.tests.strategies.test_cycler.TestEvolvableCycler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\Axelrod\Axelrod\axelrod\tests\strategies\test_cycler.py", line 177, in test_normalized_parameters
    self.player_class(cycle=cycle, seed=1)._normalize_parameters(
  File "D:\a\Axelrod\Axelrod\axelrod\player.py", line 65, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "D:\a\Axelrod\Axelrod\axelrod\strategies\cycler.py", line 119, in __init__
    cycle, cycle_length = self._normalize_parameters(cycle, cycle_length)
  File "D:\a\Axelrod\Axelrod\axelrod\strategies\cycler.py", line 132, in _normalize_parameters
    raise InsufficientParametersError(
axelrod.evolvable_player.InsufficientParametersError: Insufficient Parameters to instantiate EvolvableCycler
```
despite this PR not changing anything in the actual code base.

also, the read the docs build failing despite me literally copying the files exactly from the successful #1419 setup

**Comment by drvinceknight** [comment]
> also, the read the docs build failing despite me literally copying the files exactly from the successful #1419 setup

Here's the failure traceback on rtd:

```
$ python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
Collecting docutils<=0.17 (from -r docs/requirements.txt (line 1))
  Downloading docutils-0.17-py2.py3-none-any.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.1/575.1 kB 93.6 MB/s eta 0:00:00
ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 1.23.5 Requires-Python >=3.8; 1.24.0 Requires-Python >=3.8; 1.24.0rc1 Requires-Python >=3.8; 1.24.0rc2 Requires-Python >=3.8; 1.24.1 Requires-Python >=3.8; 1.24.2 Requires-Python >=3.8; 1.24.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement numpy==1.24.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy==1.24.3
```

**Comment by alexhroom** [comment]
my bad - i mistakenly put the yaml in the docs/ directory rather than the root directory.

**Comment by marcharper** [comment]
LGTM

**Pull request merged**
