### PR TITLE
Add type hints to averagecopier

### PR DESCRIPTION
**Pull request by janga1997**
#808 
mypy produces no errors. Same issue with the tests as #846 .

### CODE REVIEW

**Comment by janga1997** [comment]
@drvinceknight What exactly is the conflict here?

**Comment by drvinceknight** [comment]
> @drvinceknight What exactly is the conflict here?

You seem to have a slightly older version of `type_tests.sh` on your branch. If you can pull an up to date master branch, rebase (or merge) then you will be able to see the merge conflict clearly.

Let us know if any of that is unclear.

**Comment by janga1997** [comment]
@drvinceknight I've messed up both this branch and that of `plot.py`. Is there any way to backtrack to before?

**Comment by janga1997** [comment]
Would it be easier to delete the local branch and pull from the branch at my fork again?

**Comment by drvinceknight** [comment]
> Would it be easier to delete the local branch and pull from the branch at my fork again?

Yup, that's probably the easiest thing to do in this case. If adding the module to `type_tests.sh` causes too much of a headache don't worry we can do that at a later point. :)

**Comment by janga1997** [comment]
@drvinceknight Fortunately it worked. :)

**Comment by drvinceknight** [comment]
> @drvinceknight Fortunately it worked. :)

Great!

**Pull request merged**
