### PR TITLE
258 - Changing heatmap colormap

### PR DESCRIPTION
**Pull request by drvinceknight**
This changes the default to `YlGnBu`, take a look at #258 for other example heatmaps...

### CODE REVIEW

**Comment by drvinceknight** [comment]
Something strange happened with the eco graphs... **Don't merge.**

**Comment by drvinceknight** [comment]
This one has me stumped, the *eco* plots seems broken for me:

basic_strategies_reproduce

I have tried:

- Different machine
- Virtualenv to make sure I was using the right version of matplotlib

I have tried this on both `master` and my `258` branch... I'm going to open an issue...

**Comment by drvinceknight** [comment]
As mentioned on #261 could someone please rerun the whole results and push to this branch so that it can be merged in?

**Comment by marcharper** [comment]
Ok I updated the assets and rebased; looks like I picked up a few commits from my branch (branched from upstream after #257). All the plots look right now.

**Comment by drvinceknight** [comment]
Thanks! :+1: I'll let @meatballs or @langner press the button :)

**Pull request merged**
