### PR TITLE
Update setup.py to include python 3.7 instead of 3.5

### PR DESCRIPTION
**Pull request by marcharper**

### CODE REVIEW

**Comment by drvinceknight** [comment]
I suspect we've already discussed this and I'm just forgetting but is there a reason why we cannot add 3.7 and keep 3.5?

**Comment by marcharper** [comment]
No reason, just matching with Travis. We "officially" support the two latest released of Python but I don't see any problem leaving 3.5 in.

**Comment by meatballs** [comment]
I can't remember precisely what they were, but there were some things we wanted to do that were only supported in 3.6+ and we decided to leave them until 3.7 came along and we could drop 3.5

**Comment by drvinceknight** [comment]
Let's go ahead and merge, if something comes up that needs us to bring 3.5 back in then we can always do that.

**Pull request merged**
