### PR TITLE
Pickle fix

### PR DESCRIPTION
**Pull request by marcharper**
Quick fix for #391 using cloudpickle. Please see the discussion at #391.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Travis errored out:

```
Collecting cloudpickle==0.11 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement cloudpickle==0.11 (from -r requirements.txt (line 3)) (from versions: 0.1.0, 0.1.1)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).
  No distributions matching the version for cloudpickle==0.11 (from -r requirements.txt (line 3))
The command "pip install -r requirements.txt" failed and exited with 1 during .
Your build has been stopped.
```

Just reseting the build in case...

**Comment by marcharper** [comment]
Shoudl be 0.1.1 I guess, let me fix...

**Comment by drvinceknight** [comment]
What's the status on this? The discussion on #391 seems to suggest doing something different?

**Comment by marcharper** [comment]
I think we should merge this now, or disable caching, until we decide on a permanent fix. Right now the tournaments run but they crash with an error when Backstabber is cached.

**Comment by drvinceknight** [comment]
Merged as it's a bug.

**Comment by marcharper** [comment]
Just note that this needs #390 to fix the bug still, as far as I can tell from my testing.

**Pull request merged**
