### PR TITLE
Only instantiate the logHandler in use

### PR DESCRIPTION
**Pull request by meatballs**
#438

### CODE REVIEW

**Comment by drvinceknight** [comment]
Looks good to me, is it possible to write a test for this?

Either way: :+1:

**Comment by meatballs** [comment]
> is it possible to write a test for this?

I'm sure it is, but I was feeling too lazy to tackle it since we don't have any tests at all for utils.py!

**Comment by drvinceknight** [comment]
> I'm sure it is, but I was feeling too lazy to tackle it since we don't have any tests at all for utils.py!

Cool, have opened #482 I'm happy to tackle that.

**Comment by meatballs** [comment]
:+1:

**Pull request merged**
