### PR TITLE
BigResultsSetFromFile

### PR DESCRIPTION
**Pull request by marcharper**
First attempt at a BigResultsSet re: #573.

### CODE REVIEW

**Comment by drvinceknight** [comment]
#585 should fix the py3.4 bug (issue with an upstream bug in pyparsing).

**Comment by marcharper** [comment]
I haven't actually tested this on a large tournament, obviously we don't want to add that to Travis. I'll run some longer tournaments locally and report back.

**Comment by drvinceknight** [comment]
:+1: Looking neat. Hadn't seen this kind of stuff before.

**Comment by marcharper** [comment]
Unfortunately this turned out to be really slow and we're better off reloading from disk as needed.

**Comment by drvinceknight** [comment]
How slow is slow because if the memory consumption is not crazy (currently the full tournament uses up 10GB of Ram) it could still be worthwhile? 

This isn't about speed but about memory.

**Comment by marcharper** [comment]
It took more than 30 minutes to load the 8gb file into the shelve (I stopped it before it finished), and took around 1.5 gb of memory. I'm sure we can do better by simply wrapping the interactions object into a generator and reading it off disk multiple times (at least once for `scores` and once for `wins`). I was just trying to change as little code as possible with this PR and it didn't work out as well as I'd hoped.

**Comment by drvinceknight** [comment]
Cool. :)

**Pull request closed without merging**
