### PR TITLE
Pushing Mutual strategies from mutual2

### PR DESCRIPTION
**Pull request by ranjinidas**

### CODE REVIEW

**Comment by ranjinidas** [comment]
Should I just remove first_play_test altogether? There are two failing right now because of random_choice().

**Comment by marcharper** [comment]
What we usually do is to set the random seed to something specific so that we know what the move will be each time. We'll add extra tests as needed, so feel free to remove the failing tests for now.

**Comment by ranjinidas** [comment]
Okay, just removed them and I'll look out for the extra tests and random seed so I know what to use next time. Thanks!

**Comment by marcharper** [comment]
Great I'll take it from here.

**Comment by marcharper** [comment]
I moved the new commits to #686 .

**Pull request closed without merging**
