### PR TITLE
adds tournament length to player2 on self-interactions

### LINKED ISSUE #253: BackStabber and DoubleCrosser self interactions error
There appears to be a problem with interactions between two DoubleCrosser or BackStabber players where the scores are being calculated incorrectly.

For example:
```
import axelrod

p1, p2 = axelrod.BackStabber(), axelrod.BackStabber()
turns = 10
p1.tournament_length = turns
p2.tournament_length = turns

r = axelrod.RoundRobin([p1, p2], axelrod.Game(), turns)

print r.play()
```

gives:
```[[16.0, 6], [26, 16.0]]```

when I'd expect to see:
```[[26, 26], [26, 26]]```

I get exactly the same result for DoubleCrosser.

I've tried several other deterministic strategies and found no problems with any of them.

### PR DESCRIPTION
**Pull request by meatballs**
fixes #253

### CODE REVIEW

**Comment by marcharper** [comment]
I'm fine with this. The reset before the deepcopy does increase the efficiency of the copy though, since it's not copying any unnecessary history or internal variables. (I know it gets reset later.) We could also reset after each head-to-head match is over.

**Comment by meatballs** [comment]
At the point where the copy takes place, the object has only just been instantiated. It has no history or anything else, so I don't believe the reset is necessary.

We reset just before each interaction - lines 105 and 106 of RoundRobin - so I'm not sure what a reset afterwards would add.

**Comment by marcharper** [comment]
Ok, thanks for the explanation. It seemed like the reset was making a difference in runtime on my machine, but it's slight and it could be do to other things (perhaps other loads on the machine).

This is on :+1: to merge IMO.

**Comment by marcharper** [comment]
Merging under the unspoken "bug fix doesn't need two people" rule.

**Pull request merged**
