### PR TITLE
adds additional email addresses

### PR DESCRIPTION
**Pull request by meatballs**
#130

### CODE REVIEW

**Comment by drvinceknight** [comment]
I read somewhere about the multiple email address thing and the suggestion was to just have one (to ensure there was no confusion with some messages being sent to some people and not all at times). I think this makes a lot of sense. 

The suggestion was perhaps to create an email list but I thought this was potentially overkill for this (modest) so I was happy to be the central email and just relay but perhaps I'm wrong and setting up a Google group is not a bad idea (costs nothing). 

I don't think having multiple email addresses there is a good thing though (not at all to not pass on credit or anything -  just to make sure it's clear what to do if someone wants to get in touch...).

**Comment by meatballs** [comment]
No problem - I was really only looking for something simple to see if we could usefully use the idea of creating PRs against branches other than master. Feel free to dump it!

**Comment by drvinceknight** [comment]
What do you think though? I like the idea of a Google group? No harm
right... (have setup quite a few, should have probably just done it for
this)...

I think the PR thing works well for this sort of stuff.

**Comment by meatballs** [comment]
> I like the idea of a Google group?

Why not? We've used just about ever other tool out there so far, so why not a Google Group?!!! Seriously, it seems a perfectly good way to create a mailing list to me.

**Comment by drvinceknight** [comment]
Cool, can you create it? (I'm on a train with rubbish signal but if awkward
I can set it up later :))

You'll be able to add Karol and I as managers or something like that but
who cares as long as it's public and anyone can email it and read it :)

**Comment by drvinceknight** [comment]
Thanks for creating the group, you seem to have created a private one? Should it not be a public one that everyone can see? (You know for when millions of people use this... :confused: )

**Comment by meatballs** [comment]
It's public in that anyone can write to it but private in that only the three of us are members.

I thought the intention was simply to provide an address to PyPi for the authors of the package, rather than to create an open community for discussion. Surely we already have github issues and gitter for that?

**Comment by drvinceknight** [comment]
Ah fair dues: I didn't realise anyone could write to it. Let me attempt to
send an email to see what happens :)

Vince

**Comment by drvinceknight** [comment]
Just seen that you've done that... Now to go and figure out why I did not
see the email...

**Pull request merged**
