### PR TITLE
WIP: Fix compute features and retrain ann

### LINKED ISSUE #1172: function 'compute_features' in ANN.py
Thanks for your work. line 72 in ANN.py, 'my_previous_d = 0 if player.history[-1] == D else 0', i think it should be 'my_previous_d = 1 if player.history[-1] == D else 0'.
Is it a typo or you did that on purpose?  And is the weights trained under this code?
Looking forward for ur reply, thanks.

### PR DESCRIPTION
**Pull request by drvinceknight**
This closes #1172

@marcharper note that I trained ANNNoise with a hidden layer of size 10 due to the
docstring. This was in fact an incorrect (the layer had size 5) docstring but retraining took
quite a while so I went with changing the layers.

I've also archived the training data (link now in docstrings of strategies and also here: doi.org/10.5281/zenodo.1306598) so please check if I've gotten the moving of that to the right place in the repo right :)

I've run a quick tournament (still takes a little while) and things don't seem to have changed much:

```
>>> import axelrod as axl
>>> axl.seed(0)
>>> players = [s() for s in axl.strategies if not s.classifier["long_run_time"]]
>>> tournament = axl.Tournament(players=players, repetitions=20)
>>> results = tournament.play(processes=0)
>>> results.ranked_names[:10]
['Evolved HMM 5',
 'EvolvedLookerUp2_2_2',
 'Evolved ANN 5',
 'Evolved FSM 16',
 'PSO Gambler 2_2_2',
 'Evolved ANN',
 'Evolved FSM 16 Noise 05',
 'Evolved FSM 4',
 'PSO Gambler 1_1_1',
 'Evolved ANN 10 Noise 05']

```

### CODE REVIEW

**Comment by marcharper** [comment]
I think we should leave it at 5 since that's what we used in the published papers (sorry I know it's a pain to retrain).

**Comment by drvinceknight** [comment]
> I think we should leave it at 5 since that's what we used in the published papers (sorry I know it's a pain to retrain).

Sure, I'll retrain now.

**Comment by drvinceknight** [comment]
I'll leave this PR open until it's done.

**Comment by marcharper** [comment]
Looks fine to me pending tests passing

**Comment by drvinceknight** [comment]
> Looks fine to me pending tests passing

Looks like we're getting intermittent failures for some reason on CI... I'll keep kicking the tires until this passes but also open an issue with whatever the problem is...

**Comment by drvinceknight** [comment]
Tests have passed now @marcharper :+1: :) (I've opened #1187 to keep an eye on the inconsistency.)

**Pull request merged**
