### PR TITLE
Added strategies Desperate, Hopeless, Willing, and Grim. 

### PR DESCRIPTION
**Pull request by ranjinidas**
All four strategies are contained in the file mutual, since they follow a similar theme. The commits became a little messy after I had to undo a push.

### CODE REVIEW

**Comment by marcharper** [comment]
Hi @ranjinidas! Thanks for the contribution.

I think you may have added the build directory post installation to the repository. Can you try adding a new commit that removes the files in the build directory. If you need help with that just let me know.

Also I believe that GRIM is the same as Grudger -- I think that the other three strategies are not yet in the library :) Let's check that before merging.

**Comment by drvinceknight** [comment]
These look great @ranjinidas, your Grim strategy is not the same as the Grudger strategy in the library but as @marcharper said that is another common name for Grudger (a strategy that will defect forever if ever defected against). Did you have a reason for that particular name? Perhaps we could find another one.

I don't think the other strategies are in there yet but once you remove the build files it'll be easier to look through and be sure :)

The tests failing on travis are two simple doctests:

1. `len([s for s in axl.strategies if s().classifier['memory_depth']==1])` is returning 27 now and was returning 21 (not sure why there's a jump of 6 strategies...)
2. The other is in the `docs/tutorials/advanced/setting_a_seed.rst`, everything is still working but the way I've written that isn't great. I'm going to open a PR to your branch with a way that makes that right.

**Comment by drvinceknight** [comment]
The [PR is open](https://github.com/ranjinidas/Axelrod/pull/1) but it looks like it's grabbed quite a few commits (not too sure why, I branched from your branch...). The change it makes is pretty simple so you might just want to implement it yourself. 

You can see it here: https://github.com/ranjinidas/Axelrod/pull/1/commits/52452f75569ad96a08f524b42fcfe53990fae33b

Let us know if we can help with anything else :) 👍

**Comment by drvinceknight** [comment]
> The PR is open but it looks like it's grabbed quite a few commits (not too sure why, I branched from your branch...). The change it makes is pretty simple so you might just want to implement it yourself.
> 
> You can see it here: ranjinidas@52452f7

Ignore all that (sorry!).

I see now that your master branch is a few commits behind the master so the change I'm suggesting wouldn't make much sense as that file isn't there. I've opened a simple PR that once it  goes in will make that test pass.

**Comment by ranjinidas** [comment]
Hi @marcharper and @drvinceknight! Thanks for the feedback. I got the strategies here: http://www.rug.nl/research/gelifes/tres/publications/_pdf/vdberg_weissing_prsb_2015.pdf, where Grim was defined as "only cooperates after mutual cooperation". Do you have any suggestions for what I could change the name to? 

Also, sorry about getting the build directory in there. I'll remove it and commit again.

**Comment by marcharper** [comment]
@drvinceknight Are you sure they aren't the same? Based on the reference, it looks like a memory-one strategy with four-vector (1, 0, 0, 0), which seems like a strategy that cooperates initially and then defects forever if ever defected against. (Notice that all of the strategies in the reference are memory-one and that we have many; would be nice to have them all).

I think we're supposed to assume that GRIM cooperates on the first move (despite the description in the reference and @ranjinidas's implementation) -- otherwise it will never cooperate. Based on that assumption I think it is the same as grudger.

Finally, we (me, I suppose) should prioritize #225 and also a dictionary or convenient reference in the docs for strategies that have multiple common names.

**Comment by drvinceknight** [comment]
Sorry you're completely correct. It is the same as Grudger! So it can be
removed.

**Comment by drvinceknight** [comment]
After @meatballs merged #685 the only test that is now failing is this doctest:

```
>>> len([s for s in axl.strategies if s().classifier['memory_depth']==1])
21
```

That's in: `docs/tutorials/advanced/classification_of_strategies.rst`.

Your branch is returning 27. Not entirely sure why that's gone up by 6 but perhaps once you've removed the build files it'll be easier to figure it out. :) 👍

**Comment by drvinceknight** [comment]
This looks great now. As far as I can see it's just that one doctest that needs fixing (now indeed expecting 24) 👍

**Comment by ranjinidas** [comment]
Thanks!

**Comment by marcharper** [comment]
Two more things, if you don't mind:
* Can we double check what the strategies do on the first move? Just want to make sure we've got it right, since for these types of strategies the often either always cooperate first or behave randomly
* Can you squash commits e4e4fd4 through 4280e15 to a single commit? This will keep the files in the build directory from being added to the git tracking objects. To do so, run the following commands, assuming your repositories
```
git branch backup
git rebase -i origin master
```
This will bring up a list of commits. You'll need to change "pick" to "squash"  for commits 82a27cb through 4280e15. Git will ask you to modify the commit message (the default is fine).

Then run `git push -f` (to your master branch on github). If you need help with this just let me know. I've got a local copy of your branch, but I want to make sure you get credit for your work (so it's best if you squash the commits).

**Comment by drvinceknight** [comment]
The mutual module needs to be added to the documentation so that the three strategies are automatically added to the index in the docs. This is explained in the last paragraph here http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/adding_the_new_strategy.html  (on my phone and about to head to bed, can be more helpful tomorrow if needed :)).

**Comment by ranjinidas** [comment]
@marcharper The strategy does not specify a first move. I thought since each strategy definition says that the player /always/ plays a move unless prompted otherwise, it would be safe to have the start move set to the default move. I can remove the first move test, though, if you think I should. 

@drvinceknight Added it in! :)

**Comment by marcharper** [comment]
In the reference it says: " In addition, a separate locus determines an individual’s
behaviour in the first round; this locus can take on any value
of the unit interval..."

and also

"At the beginning of each simulation, the loci of all indi-
viduals were initialized at random: initial values for the
locus that determines the behaviour in the first round were
drawn from a normal distribution with mean 0.5 and stan-
dard  deviation  0.1;  the  four  binary  loci  in  the  1 : 1
architecture were assigned a 0 or a 1 with equal probability;
and the nine loci encoding the connection weights and
thresholds in the neural network architecture were assigned
values that were drawn from a normal distribution with
mean 0 and standard deviation [sigma_N]"

So it looks like the first move is random somehow.  Maybe that's what we should do: `random_choice()` from our `axelrod.random_.py` file.

**Comment by ranjinidas** [comment]
Okay, I will look into that! Thank you! I'm also having some issues with the rebase. I mentioned them on Gitter, but will bring it over here if you prefer.

**Comment by marcharper** [comment]
Closing re: #686, please move discussion there and re-open if there are any issues with my rebase.

**Pull request closed without merging**
