### PR TITLE
Coverage Again

### PR DESCRIPTION
**Pull request by meatballs**
Don't merge this

### CODE REVIEW

**Comment by meatballs** [comment]
that's getting closer!

**Comment by meatballs** [comment]
Gotcha!!

Don't merge this. I still have some work to do on this, but at least it's working at last!!

**Comment by drvinceknight** [comment]
Sweet :)

**Comment by meatballs** [comment]
This is good to go now!

**Comment by meatballs** [comment]
And I've switched off the annoying comments coming from coveralls.io

**Pull request merged**
