### PR TITLE
New Strategy Anti Tit For Tat

### PR DESCRIPTION
**Pull request by marcharper**
A strategy that always plays the opposite of the opponents previous move.

### CODE REVIEW

**Comment by langner** [comment]
Is the only different with SuspiciousTitForTat that the first move is C instead of D?

**Comment by marcharper** [comment]
Actually suspicious Tit For Tat is incorrectly named. From [this reference](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0077886):

"Suspicious Tit-for-Tat (which starts with defection and then repeats the opponent’s previous move), Always Defect, and an Anti-Tit-for-Tat strategy (which always plays the opposite of the opponent’s previous move)"

So Suspicious TFT should be TFT but with a difference first move. But yes that is the only difference with the current STFT implementation. (It's an important difference though.)

**Comment by marcharper** [comment]
I renamed the existing sTFT to Bully and added the version of sTFT as described in the reference (with tests).

**Comment by marcharper** [comment]
If you run the tournament now you can see there is a not insignificant difference between Bully, sTFT, aTFT, and TFT

**Comment by langner** [comment]
I think at some point the original ATFT got merged with BULLY, which were once separate. Anyway, this looks nice. I only did a small refactoring for these strategies, see marcharper/Axelrod#1

**Pull request merged**
