### PR TITLE
Adjust that S&R is now implemented.

### PR DESCRIPTION
**Pull request by drvinceknight**

### CODE REVIEW

**Comment by meatballs** [comment]
Github threw an error when I tried to merge this, but it's now complaining about a conflict. 12f1e09 appears in the master branch, so I reckon it actually did the merge and this PR should be closed.

**Comment by drvinceknight** [comment]
How strange: that's never happened before :)

Definitely looks like it all went in: https://github.com/Axelrod-Python/Axelrod/blob/master/docs/reference/overview_of_strategies.rst

I agree let's close (we can always reopen when the gates of hell burst open.)

**Comment by meatballs** [comment]
Didn't mean to delete that comment - I was attempting to edit it!

**Comment by drvinceknight** [comment]
> Didn't mean to delete that comment - I was attempting to edit it!

np :)

**Pull request closed without merging**
