### PR TITLE
Add type hints to oncebitten, prober, punisher, rand

### PR DESCRIPTION
**Pull request by janga1997**
#808 
Same error as #860 , `mypy` cannot infer type for empty containers. See [here](https://github.com/python/mypy/issues/1534).

### CODE REVIEW

**Comment by drvinceknight** [comment]
> Same error as #860 , mypy cannot infer type for empty containers. See here.

Ok that's good to know. I'm not sure what the best way to deal with this is...

**Comment by janga1997** [comment]
@drvinceknight Apparently a simple workaround is to add the comment 
`# type: List[Action]`
we can explicitly annotate variables with these type of comments in mypy. 
I believe this is the best solution right now, as `mypy` has no plans to fix this issue.

**Comment by drvinceknight** [comment]
> I believe this is the best solution right now, as mypy has no plans to fix this issue.

It looks good to me! Nice find :)

**Comment by janga1997** [comment]
@meatballs Can you merge this PR? And a couple other type hint PRs too which have been reviewed?

**Comment by drvinceknight** [comment]
> @meatballs Can you merge this PR? And a couple other type hint PRs too which have been reviewed?

Hi @janga1997 we all keep an eye on the PRs. Sorry it's taking us a little while to merge them but there's no need to ping us. We just all happen to be busy right now they will be merged as soon as possible :)

**Comment by janga1997** [comment]
@drvinceknight Sorry for the trouble. Won't happen again.

**Comment by drvinceknight** [comment]
No trouble at all. All these contributions are awesome. Just a shame they're coming at a time when we seem to all be busy :D

**Comment by janga1997** [comment]
@drvinceknight I understand. And all the core maintainers have full time jobs. 
And you are working while traveling.
I'm just a bored college junior here :-)

**Comment by janga1997** [comment]
@meatballs Why are the errors showing up after merging master? Is it anything of consequence?

**Comment by meatballs** [comment]
No, it's just that I merged it before Travis had run again, so github thinks there was a problem

**Pull request merged**
