### PR TITLE
Move common play functionality

### PR DESCRIPTION
**Pull request by gaffney2010**
We make a BasePlayer, with a common play function.  This play function looks at a GameParams object (passed at initialization) to use get_actions, which says how to get a set of actions from the players playing; it then saves history and returns outcomes.  (To save the GameParams object, we need to change pickling to dilling in many places.)  In order to save history, we need to make a common BaseHistory class, along with a history factory that we store to GameParams.

### CODE REVIEW

**Comment by gaffney2010** [comment]
The tests are failing on Windows, because I guess the parallelizations pickle by default and I added a lambda to the Player class.  I could avoid this by, for example, making a get_game_params method that gets overwritten for each player type...

**Comment by marcharper** [comment]
Yeah multiprocessing pickles objects that pass through it. Can we stipulate that each "Player type" specify a history class in its definition, and the abstract base class can just use something generic?

**Comment by marcharper** [comment]
Is there no way to avoid use of dill?

**Comment by gaffney2010** [comment]
Closing this for now.  The work to get it running in Windows may be a little bigger than I thought.

**Pull request closed without merging**
