### PR TITLE
Add back in noise parameter to tournament

### PR DESCRIPTION
**Pull request by marcharper**
We lost the pass through of the noise parameter when tournament was refactored.

### CODE REVIEW

**Comment by marcharper** [comment]
I'm testing the fix now...

**Comment by drvinceknight** [comment]
That's a funny one to have missed. Could you add a copy of the integration test I tweaked in the other PR to include a noisy tournament with all strategies (to avoid this happening again) ? Out on a dog walk, if I'm not clear I can add that in a bit.

**Comment by marcharper** [comment]
I'm writing a test now.

**Comment by drvinceknight** [comment]
Cool, as soon as Travis is content I'll merge as a bug fix and release 1.0.1.

**Pull request merged**
