### PR TITLE
Make ecological plots more readable

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Just checking that the change re 'Make ecological paths more readable' is a change to making the axis for the plots logarithmic?

**Comment by langner** [comment]
> ust checking that the change re 'Make ecological paths more readable' is a change to making the axis for the plots logarithmic?

Yes, plus some other minor things. And I meant plots not paths :)

**Comment by marcharper** [comment]
The plots are definitely better. The only thing I'd like to see added is for the ecological simulation to run a bit longer in some cases, since e.g. assets/strategies_reproduce.png looks like some additional things might happen if it were to run a bit longer.

**Comment by langner** [comment]
> The plots are definitely better. The only thing I'd like to see added is for the ecological simulation to run a bit longer in some cases, since e.g. assets/strategies_reproduce.png looks like some additional things might happen if it were to run a bit longer.

Sure, that can be done. Probably backstabber will just stab everyone into oblivion. We should do something about that...

**Comment by marcharper** [comment]
Hi @langner -- can you merge in master or rebase and then rerun update_results.sh? Since I added some new strategies and merged that first, the assets in your commit won't have them. (Sorry about that!)

**Comment by langner** [comment]
Here you go!

**Comment by drvinceknight** [comment]
I'm happy for this to go in @marcharper if you wanted to press go when you are :)

**Comment by marcharper** [comment]
:thumbsup: :)

**Pull request merged**
