### PR TITLE
Add custom matches

### PR DESCRIPTION
**Pull request by drvinceknight**
This is an extension of #1394.

In practice it adds very little to the source code: just makes it possible to pass a match class to the Moran Process.

I originally wanted to do the same with the tournament however the way we calculate results for the tournament is a bit more complex and with `5.0.0` in mind might need a bit more discussion.

So this PR is mainly documentation with a tutorial to show how to reproduce the [Krapohl, S., Ocelík, V. & Walentek, D.M. The instability of globalization: applying evolutionary game theory to global trade cooperation. Public Choice 188, 31–51 (2021). https://doi.org/10.1007/s11127-020-00799-1](https://link.springer.com/content/pdf/10.1007/s11127-020-00799-1.pdf)
 paper

### CODE REVIEW

**Comment by drvinceknight** [comment]
I do not know why the rtds sphinx docs build is failing. Here's the end of the traceback:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/1397/lib/python3.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/1397/lib/python3.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable
The full traceback has been saved in /tmp/sphinx-err-b26hdrli.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Review by marcharper — APPROVED** [review]

**Comment by marcharper** [comment]
```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/axelrod/envs/1397/lib/python3.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable
```

If it's a generator it needs to be in a list context before the first element can be accessed. Maybe bumping some versions up will help?

**Comment by drvinceknight** [comment]
> Maybe bumping some versions up will help?

I'll try a few things :+1:

**Comment by drvinceknight** [comment]
Someone found the fix, it's related to  https://github.com/sphinx-doc/sphinx/commit/13803a79e7179f40a27f46d5a5a05f1eebbcbb63 I have pinned docutils.

**Pull request merged**
