### PR TITLE
Add a thesis to citations

### PR DESCRIPTION
**Pull request by marcharper**

### CODE REVIEW

**Comment by marcharper** [comment]
Error appears unrelated (black wants to reformat some files).

**Comment by Nikoleta-v3** [comment]
For some citations we use brackets for the publication year and for some we don't 🤷🏻 Do we care about this? Do we want to be consistent?

**Comment by drvinceknight** [comment]
> Error appears unrelated (black wants to reformat some files).

This could be due to an update of black.

**Comment by drvinceknight** [comment]
Have opened https://github.com/Axelrod-Python/Axelrod/pull/1400 which is a PR to this branch with an updated version of black. (Do we want to pin black?)

**Comment by drvinceknight** [comment]
This looks like hypothesis has stumbled on an edge case?

**Comment by drvinceknight** [comment]
I believe this is good to go.

**Pull request merged**
