### PR TITLE
Added docstrings to strategy methods

### PR DESCRIPTION
**Pull request by caddycarine**
- Added docstrings to strategy methods so they don't display the default placeholder docstring from the Player class.
- Corrected (comments) typos in player, tournament, and _strategy_utils
- Extracted calculation of cooperation ratio into a new method in averagecopier.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Thanks for this @caddycarine.

I believe the test are failing because of a small error in the docs that was fixed in #1372. Specifically in `docs/tutorials/advanced/setting_a_seed.rst` where:

```
>>> import axelrod as axl
>>> players = (axl.Random(), axl.Cooperator(), axl.MetaMixer())
>>> tournament = axl.Tournament(players, turns=5, repetitions=5, seed=201)
>>> results = tournament.play(processes=2)
>>> tournament2 = axl.Tournament(players, turns=5, repetitions=5, seed=201)
>>> results2 = tournament.play(processes=2)
>>> results.ranked_names == results2.ranked_names
True
```

should be:

```
>>> import axelrod as axl
>>> players = (axl.Random(), axl.Cooperator(), axl.MetaMixer())
>>> tournament = axl.Tournament(players, turns=5, repetitions=5, seed=201)
>>> results = tournament.play(processes=2)
>>> tournament2 = axl.Tournament(players, turns=5, repetitions=5, seed=201)
>>> results2 = tournament2.play(processes=2)
>>> results.ranked_names == results2.ranked_names
True
```

(There's actually two spots where that occurs).

There are two fixes here:

1. Rebase the up to date `dev` branch. (Preferred)
2. Tweak that yourself and the tests should pass. (Potential for merge conflicts)

**Comment by drvinceknight** [comment]
The CI is failing on `black` <https://github.com/psf/black>:

```
would reformat /home/runner/work/Axelrod/Axelrod/axelrod/strategies/averagecopier.py
36
would reformat /home/runner/work/Axelrod/Axelrod/axelrod/strategies/hunter.py
37
would reformat /home/runner/work/Axelrod/Axelrod/axelrod/tests/strategies/test_meta.py
```

Could you run:

```
python -m black -l 80 .
```

at the root of the repo (should modify those 3 files).

**Comment by drvinceknight** [comment]
There seems to be a merge conflict in `test_meta` if you could rebase/merge `dev` please.

**Review by drvinceknight — APPROVED** [review]
Looks  good to me. Thank you @caddycarine.

**Comment by marcharper** [comment]
Why are so many files affected? I thought we ran black recently.

**Comment by drvinceknight** [comment]
> Why are so many files affected? I thought we ran black recently.

We did so I'm not too sure but I **think** this is because of how the commits were applied. Looks like a commit from the "applying black" PR 87fa66e was perhaps  cherry picked which added merge conflicts and then black was run again. So my guess is that a local rebase would clean up the history.

It could be worth:

```
$ git checkout dev
$ git pull origin dev
$ git checkout -b add_docstrings
$ git cherry-pick 5639e7f
$ python -m black -l 80
$ git commit # if necessary
```

If I'm reading everything correctly the only commit that's actually needed in this PR is 
 5639e7f

**Comment by marcharper** [comment]
@caddycarine After you follow the commands above, you'll need to open a new PR from the add_docstrings branch

**Comment by caddycarine** [comment]
> @caddycarine After you follow the commands above, you'll need to open a new PR from the add_docstrings branch

After following the commands, do i rebase onto master before opening the PR?

**Comment by drvinceknight** [comment]
The second command `git pull origin dev` would mean that you don't need to as you would be branch from the latest version of `dev` (note that there is no `master` branch #1352 but the `dev` branch essentially serves that purpose now).

**Comment by drvinceknight** [comment]
Closing this as #1377 has been merged.

**Pull request closed without merging**
