### PR TITLE
New strategies

### PR DESCRIPTION
**Pull request by marcharper**
Some additional strategies that behave cyclically and non-cyclically. There are now multiple strategies that hunt for other strategies that use patterns or cycles, but not that many strategies that actually behave in such a way.

This is post-deletion of assets #276.

### CODE REVIEW

**Comment by meatballs** [comment]
Could we have something in the docs for the new strategies?

**Comment by uglyfruitcake** [comment]
Sorry if I'm missing something, but is Fool Me Forever the same as Opposite Grudger?

**Comment by marcharper** [comment]
@uglyfruitcake They are not quite the same. FMF doesn't start playing 'C' until the opponent plays 'D'; for opposite grudger it's after the opponent plays 'C'.

I'll add some info to the docs.

**Comment by marcharper** [comment]
Rebased onto the new upstream and added some documentation.

**Comment by meatballs** [comment]
:+1:

**Pull request merged**
