### PR TITLE
Adds coveralls service and badges

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by meatballs** [comment]
Don't merge this yet. I'm still mucking about with it and I can only get it run by committing changes to this branch.

**Comment by meatballs** [comment]
Not working properly. I've logged an issue here:

https://github.com/coagulant/coveralls-python/issues/75

**Comment by drvinceknight** [comment]
Awesome: I looked in to this briefly, it'll be a great addition when it's ready.

**Comment by meatballs** [comment]
There's an alternative package for sending data to coveralls.io I'm going to set that up on a different branch and see if it works any better.

**Comment by meatballs** [comment]
You can see the builds appearing here: https://coveralls.io/r/Axelrod-Python/Axelrod

**Comment by drvinceknight** [comment]
That is cool. Can this now be merged?

**Comment by drvinceknight** [comment]
https://coveralls.io/builds/2563671 gives details as to where we are missing tests. Very cool.

**Comment by drvinceknight** [comment]
97% is pretty good though I reckon! :)

**Comment by meatballs** [comment]
No - the only data that successfully got there so far is from me running it locally. Still having problems with Travis

**Comment by drvinceknight** [comment]
Ah right: I understand. :+1:

**Comment by meatballs** [comment]
Just waiting to see how the other package does on PR #194

**Comment by meatballs** [comment]
This isn't going to work. unittest fails to create the .coverage file when run on Travis. All the stuff I can find online suggest using nose or py.test to run the tests instead but neither of those likes the TestPlayer Class that all our players testing inherits from.

Seems like too much work and not enough benefit to change all that.

**Comment by drvinceknight** [comment]
That's a shame...

**Comment by meatballs** [comment]
Yep. I thought it would be simple and quick to setup.

Nose and py.test are both very nice tools for running the tests, but they really don't like the TestPlayer Class. The way to fix that involves making TestPlayer inherit from object rather than TestCase but each individual player test then has to inherit from both TestPlayer and TestCase.

Doesn't seem worth it.

We could still run coverage locally and submit to coveralls.io We just can't automate that from Travis.

**Pull request closed without merging**
