### PR TITLE
166 

### PR DESCRIPTION
**Pull request by marcharper**
Reworked run_axelrod so that run_tournaments can be imported and used in other scripts without needing to construct argparse Namespace objects for the arguments. Renamed run_axelrod to run_axelrod.py (otherwise python won't import it).

Added some long versions of argparse parameters (mainly for readability and the above remark).

Moved logging outside of run_tournaments since otherwise the handlers accumulate and the output looks like this:

## Creating Frame 00 of 40
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 2.1s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 32.0s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Finished all all_strategies tasks in 32.7s
Finished all tournaments in 66.8s

## Creating Frame 01 of 40
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 2.0s
Finished all basic_strategies tasks in 2.0s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 35.7s
Finished all strategies tasks in 35.7s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Finished all all_strategies tasks in 59.4s
Finished all all_strategies tasks in 59.4s
Finished all tournaments in 97.2s
Finished all tournaments in 97.2s

## Creating Frame 02 of 40
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Starting basic_strategies tournament with 10 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 2.0s
Finished all basic_strategies tasks in 2.0s
Finished all basic_strategies tasks in 2.0s
Starting strategies tournament with 10 round robins of 200 turns per pair.
Starting strategies tournament with 10 round robins of 200 turns per pair.
Starting strategies tournament with 10 round robins of 200 turns per pair.
Finished all strategies tasks in 37.8s
Finished all strategies tasks in 37.8s
Finished all strategies tasks in 37.8s
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Starting all_strategies tournament with 10 round robins of 200 turns per pair.
Finished all all_strategies tasks in 58.3s
Finished all all_strategies tasks in 58.3s
Finished all all_strategies tasks in 58.3s
Finished all tournaments in 98.2s
Finished all tournaments in 98.2s
Finished all tournaments in 98.2s

### CODE REVIEW

**Comment by drvinceknight** [comment]
This could take time to review.

My first thought (without reading much) is that you'd need to modify the `setup.py` script so that it now points at `run_axelrod.py`... 

I have to admit that I like the idea of just having an installed command line `run_axelrod` tool so I wonder if what you're doing here could have been done by importing something else? (Again though I've only had time to skim, would be great to have @meatballs and @langner's thoughts).

**Comment by drvinceknight** [comment]
Perhaps `run_tournament` can be put in it's own library file and that just imported by `run_axelrod`...

On a separate note `run_tournament` really needs to be unit tested so this is probably worth doing...

**Comment by meatballs** [comment]
I think this should be a separate piece of work  - preferably discussed on an issue before anything is started.

**Comment by meatballs** [comment]
37522b5 should be on a separate issue all by itself - that's a bug!

**Comment by drvinceknight** [comment]
Didn't notice that in here but @marcharper had another PR with that #184 , have already merged it in.

**Comment by meatballs** [comment]
I'm going to close this. I suggest we either create a new issue (or expand the scope of #156) and then use some of these commits in a branch for that issue.

**Pull request closed without merging**
