### PR TITLE
New transformers: Apologizing, Retaliating variant, Deadlock Breaking, Grudging

### PR DESCRIPTION
**Pull request by marcharper**
`RetaliateTransformer(N)`: Retaliation N times after a defection:
```
    >>> import axelrod
    >>> from axelrod.strategy_transformers import RetaliationTransformer
    >>> TwoTitsForTat = RetaliationTransformer(2)(axelrod.Cooperator)
    >>> player = TwoTitsForTat()
```

`ApologizingTransformer`: Apologizes after a round of `(D, C)`:
```
    >>> import axelrod
    >>> from axelrod.strategy_transformers import ApologyTransformer
    >>> ApologizingDefector = ApologyTransformer([D], [C])(axelrod.Defector)
    >>> player = ApologizingDefector()
```
`DeadlockBreakingTransformer`: Attempts to break `(D, C) -> (C, D)` deadlocks by cooperating:
```
    >>> import axelrod
    >>> from axelrod.strategy_transformers import DeadlockBreakingTransformer
    >>> DeadlockBreakingTFT = DeadlockBreakingTransformer(axelrod.TitForTat)
    >>> player = DeadlockBreakingTFT()
```

### CODE REVIEW

**Comment by drvinceknight** [comment]
> ApologizingTransformer: Apologizes after a round of :code:(D, C):

Is it worth making this an apology after any given sequence?

**Comment by marcharper** [comment]
Could be, but this is the "traditional" apology scenario. Maybe apologies after two (D, C) rounds for example?

**Comment by drvinceknight** [comment]
I'm happy to go with your preference but just think it could be nice to
have it completely generic. Then for example 2 (D, C)s just becomes
something like (D, C, D, C) etc...

**Comment by drvinceknight** [comment]
Thanks for  511d2ab, I'm happy with this. :+1:

**Pull request merged**
