### PR TITLE
Adding an ascii cast.

### PR DESCRIPTION
**Pull request by drvinceknight**
Not sure how everyone feel about this? I have just been playing with asciicasts and honestly feel that it's the coolest thing I've ever seen... (but I have been known to show over enthusiasm in the past...)

### CODE REVIEW

**Comment by drvinceknight** [comment]
You can find it here: https://asciinema.org/a/18590

**Comment by langner** [comment]
I think you made a lot of typos. Otherwise looks nice ;P

**Comment by drvinceknight** [comment]
Do you mean the typos I kept going back and fixing (I am useless :)).

Do you think I should attempt a more polished version before merging in?

**Comment by langner** [comment]
> Do you mean the typos I kept going back and fixing

Yes :) Just trying to be funny.

**Comment by drvinceknight** [comment]
Haha, you did so successfully, I laughed and then thought perhaps you wanted me to redo. Sorry if my response was a bit dry :)

**Pull request merged**
