### PR TITLE
 Added Rowsam (k58r) strategy from Axelrod's second.

### PR DESCRIPTION
**Pull request by gaffney2010**
Adapted from https://github.com/Axelrod-Python/TourExec/blob/v0.3.0/src/strategies/k58r.f

In adapting:
- I called KAM distrust_points.
- I refactored NPHA in "Coop Def cycle" modes.
- I changed the K to M comparators in lines 12-15 to a comparison on K/M, which I call points_per_turn.

### CODE REVIEW

**Comment by gaffney2010** [comment]
Yes, I can run them.  I'm on command line only until Wednesday; will run it then.

**Comment by gaffney2010** [comment]
axl_fort
axl_py

Bit of a delay on these; I had trouble getting everything setup.

**Comment by marcharper** [comment]
Looks good to me. Is it possible to generate fingerprints against more strategies? I think previously we've tossed in `Random(p)` for e.g.  `p in np.arange(0, 1, 0.05)` as well.

**Comment by gaffney2010** [comment]
Here they are.

rand_axl_fort
rand_axl_py

**Comment by drvinceknight** [comment]
Apologies for the delay in getting to this, just got back online :)

Looks great and thanks @gaffney2010 :+1:

**Pull request merged**
