### PR TITLE
moving 'C' and 'D' to axelrod constants

### PR DESCRIPTION
**Pull request by CamDavidsonPilon**
w.r.t #359 , this moves 'C' and 'D' to an `actions.py` file
```
class Actions(object):
    C = 'C'
    D = 'D'
```
(`enum` is an external lib, and I didn't want to add dependency)

@marcharper @bootandy @drvinceknight, thoughts?

### CODE REVIEW

**Comment by marcharper** [comment]
Thanks for doing this. We have a 2 maintainers approval rule for merging, so hopefully one of the others will be able to look at it soon.

Any reason that a few of the files don't use `C, D = Actions.C, Actions.D`? I presume it was simply because the occurrences were few.

**Comment by CamDavidsonPilon** [comment]
> Any reason that a few of the files don't use C, D = Actions.C, Actions.D? I presume it was simply because the occurrences were few.

Yea exactly, I used a rule of three approach: three or more occurrences => alias them.

**Comment by marcharper** [comment]
:+1: For me. My only suggestion is to add something to the docs explaining the existence of Actions, C and D. There is not much we can do on the testing front other than C != D, or just a generic test to make sure no one changes the definition of the actions.

**Comment by drvinceknight** [comment]
> There is not much we can do on the testing front other than C != D, or just a generic test to make sure no one changes the definition of the actions.

Sorry to delay this slighty, it all looks great. Could you just throw in a trival `test_actions.py`, just something that checks exactly what is suggested by @marcharper as well as perhaps `self.C,'C'` and `self.D,'D'` etc... Just to make sure that this doesn't break somewhere along the lines.

> My only suggestion is to add something to the docs explaining the existence of Actions, C and D.

Yes please :) (A sentence or two would do - the whole docs need work so at the moment it's really a question of getting something in there that at least acts as a placeholder).

**Comment by drvinceknight** [comment]
Some other merges have caused a conflict.

**Comment by CamDavidsonPilon** [comment]
Tests for `actions.py` have been added

**Comment by drvinceknight** [comment]
Yeah this is good to go :+1: thanks for the great contribution :)

**Pull request merged**
