### PR TITLE
Add how to run tests to README

### PR DESCRIPTION
**Pull request by bootandy**
Add how to run tests

### CODE REVIEW

**Comment by drvinceknight** [comment]
I think something like this was actually in the readme before and we moved it out to the docs. 

Also, with your edit to run with coveralls, if coveralls isn't installed it would fail.

**Comment by marcharper** [comment]
It's in `Axelrod/docs/contributing.rst` (and always has been, IIRC).

**Comment by drvinceknight** [comment]
There was a time before we had docs, that's probably what I'm thinking off :)

**Comment by bootandy** [comment]
You are right it is in the docs. And I shouldn't have used coverage - I just copy pasted what I saw Travis was doing.

**Pull request closed without merging**
