### PR TITLE
Use distutils version comparison.

### PR DESCRIPTION
**Pull request by drvinceknight**
I also reverted back to use if statements, which felt simpler in this (2
option) case.

### CODE REVIEW

**Comment by marcharper** [comment]
Looks fine. If it's not for master you can do whatever you want, so feel free to merge if you both agree.

**Comment by meatballs** [comment]
No problem using distutils. I was just trying to clean up the existing function.

However, passing a mutable string as a default is an anti-pattern. I  think it's better to pass None as the default.

**Comment by drvinceknight** [comment]
> However, passing a mutable string as a default is an anti-pattern. I think it's better to pass None as the default.

Cool. Have changed that.

**Comment by marcharper** [comment]
Strings are immutable so I think it's ok to use a string as a default.

**Comment by drvinceknight** [comment]
I suggest you pull this in to your branch @meatballs and possibly modify it further if you so wish, or just close it :) Any discussion can happen on the eventual PR to master 👍

**Pull request merged**
