### PR TITLE
Reduce size of tests.

### PR DESCRIPTION
**Pull request by drvinceknight**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Merging this _should_ fix everything...

**Comment by marcharper** [comment]
Hopefully we can get coverage working again and see how this fares.

**Comment by drvinceknight** [comment]
If you check the build this doesn't (shouldn't) affect coverage. Just choosing smaller strategies.

**Comment by drvinceknight** [comment]
If you scroll to the bottom of any of the logs here you should be able to see the coverage. These tests that have been causing us problems are just for the decorators in `axelrod/tests/property.py`: still 100%.

**Comment by drvinceknight** [comment]
> Just choosing smaller strategies.

Just choosing a smaller **number** of strategies. Still hitting all the lines in `property.py` file.

**Comment by marcharper** [comment]
My bad, I meant to see that Travis runs successfully, which is clearly does.

**Pull request merged**
